/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AIModelRegistryInterface extends Interface {
    getFunction(nameOrSignature: "checkAccess" | "getModelIPFS" | "hasAccess" | "modelCount" | "models" | "paymentToken" | "purchaseAccess" | "registerModel"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessPurchased" | "ModelRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'checkAccess', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getModelIPFS', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasAccess', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'modelCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'models', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchaseAccess', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerModel', values: [string, BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'checkAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModelIPFS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'modelCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'models', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchaseAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerModel', data: BytesLike): Result;
  }

  
    export namespace AccessPurchasedEvent {
      export type InputTuple = [modelId: BigNumberish, buyer: AddressLike, price: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [modelId: bigint, buyer: string, price: bigint, timestamp: bigint];
      export interface OutputObject {modelId: bigint, buyer: string, price: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModelRegisteredEvent {
      export type InputTuple = [modelId: BigNumberish, owner: AddressLike, name: string, ipfsHash: BytesLike, accessPrice: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [modelId: bigint, owner: string, name: string, ipfsHash: string, accessPrice: bigint, timestamp: bigint];
      export interface OutputObject {modelId: bigint, owner: string, name: string, ipfsHash: string, accessPrice: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AIModelRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AIModelRegistry;
    waitForDeployment(): Promise<this>;

    interface: AIModelRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    checkAccess: TypedContractMethod<
      [_modelId: BigNumberish, _user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getModelIPFS: TypedContractMethod<
      [_modelId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    hasAccess: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    modelCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    models: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, bigint] & {owner: string, registeredAt: bigint, ipfsHash: string, name: string, accessPrice: bigint }],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    purchaseAccess: TypedContractMethod<
      [_modelId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerModel: TypedContractMethod<
      [_name: string, _ipfsHash: BytesLike, _accessPrice: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'checkAccess'): TypedContractMethod<
      [_modelId: BigNumberish, _user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getModelIPFS'): TypedContractMethod<
      [_modelId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasAccess'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'modelCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'models'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, string, bigint] & {owner: string, registeredAt: bigint, ipfsHash: string, name: string, accessPrice: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'purchaseAccess'): TypedContractMethod<
      [_modelId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerModel'): TypedContractMethod<
      [_name: string, _ipfsHash: BytesLike, _accessPrice: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'AccessPurchased'): TypedContractEvent<AccessPurchasedEvent.InputTuple, AccessPurchasedEvent.OutputTuple, AccessPurchasedEvent.OutputObject>;
getEvent(key: 'ModelRegistered'): TypedContractEvent<ModelRegisteredEvent.InputTuple, ModelRegisteredEvent.OutputTuple, ModelRegisteredEvent.OutputObject>;

    filters: {
      
      'AccessPurchased(uint256,address,uint256,uint64)': TypedContractEvent<AccessPurchasedEvent.InputTuple, AccessPurchasedEvent.OutputTuple, AccessPurchasedEvent.OutputObject>;
      AccessPurchased: TypedContractEvent<AccessPurchasedEvent.InputTuple, AccessPurchasedEvent.OutputTuple, AccessPurchasedEvent.OutputObject>;
    

      'ModelRegistered(uint256,address,string,bytes32,uint256,uint64)': TypedContractEvent<ModelRegisteredEvent.InputTuple, ModelRegisteredEvent.OutputTuple, ModelRegisteredEvent.OutputObject>;
      ModelRegistered: TypedContractEvent<ModelRegisteredEvent.InputTuple, ModelRegisteredEvent.OutputTuple, ModelRegisteredEvent.OutputObject>;
    
    };
  }